version: "3.9"

services:
  # ======================
  # PostgreSQL
  # ======================
  devbox_postgres:
    image: postgres:15
    container_name: devbox_postgres
    restart: always
    environment:
      POSTGRES_USER: devbox_user
      POSTGRES_PASSWORD: devbox_pass
      POSTGRES_DB: devbox
    ports:
      - "5432:5432"
    volumes:
      - devbox_api_postgres_data:/var/lib/postgresql/data
      - ./migrate:/migrate   # <--- Mount migrations folder

  # ======================
  # Redis
  # ======================
  redis:
    image: redis:7
    container_name: devbox_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - devbox_api_redis_data:/data

  # ======================
  # Adminer (DB UI)
  # ======================
  adminer:
    image: adminer
    container_name: devbox_adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: devbox_postgres

  # ======================
  # Go App (Dev Mode)
  # ======================
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: devbox_api
    depends_on:
      - devbox_postgres
      - redis
    environment:
      APP_ENV: docker
      PORT: 8080
      DATABASE_URL_DOCKER: postgres://devbox_user:devbox_pass@devbox_postgres:5432/devbox?sslmode=disable
      REDIS_URL_DOCKER: redis://redis:6379
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "./cmd/app"]

# ======================
# Volumes
# ======================
volumes:
  devbox_api_postgres_data:
  devbox_api_redis_data:
